# Generated by Django 5.1.6 on 2025-02-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_create_schema',
            field=models.BooleanField(default=True),
        ),
    ]
